modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/dimadencep/Satin-Forge/issues"
license = "LGPL-3.0-or-later"

[[mods]]
modId = "satin"
version = "${version}"
displayURL = "https://github.com/dimadencep/Satin-Forge"
displayName = "Satin Forge"
authors = "dima_dencep, Pyrofab"
description = "Easy shaders for all modders"
logoFile = "icon.png"
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.satin]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.satin]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"