modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-3.0-or-later"

[[mods]]
modId = "satintestcore"
version = "1.0.0"
displayName = "Satin Forge Test Core"
authors = "dima_dencep, Pyrofab"
description = "Core features for all test mods"
displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.satintestcore]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.satintestcore]]
modId = "satin"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"